### ISSUE TITLE
Not working after upgrading to flutter 3.0

### ISSUE THREAD

**Issue by usamashafiqs** [CariusLars/ar_flutter_plugin#105]
e: D:\Apps\Flutter\ar_flutter_plugin\android\src\main\kotlin\io\carius\lars\ar_flutter_plugin\AndroidARView.kt: (124, 54): Null can not be a value of a non-null type String
e: D:\Apps\Flutter\ar_flutter_plugin\android\src\main\kotlin\io\carius\lars\ar_flutter_plugin\AndroidARView.kt: (127, 50): Null can not be a value of a non-null type String
e: D:\Apps\Flutter\ar_flutter_plugin\android\src\main\kotlin\io\carius\lars\ar_flutter_plugin\AndroidARView.kt: (154, 50): Null can not be a value of a non-null type String
e: D:\Apps\Flutter\ar_flutter_plugin\android\src\main\kotlin\io\carius\lars\ar_flutter_plugin\AndroidARView.kt: (166, 50): Null can not be a value of a non-null type String
e: D:\Apps\Flutter\ar_flutter_plugin\android\src\main\kotlin\io\carius\lars\ar_flutter_plugin\AndroidARViewFactory.kt: (10, 1): Class 'AndroidARViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: D:\Apps\Flutter\ar_flutter_plugin\android\src\main\kotlin\io\carius\lars\ar_flutter_plugin\AndroidARViewFactory.kt: (12, 5): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ar_flutter_plugin:compileReleaseKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Work fine with flutter 2.10.5

**Comment by Nochest** [comment]
Same issue here
